HEROES_MOD_LOADER_LEVEL_CONFIG_FILE
LEVEL_FLAG=EggFleet

PUSH_INSTRUCTION_POINTER=0x518EA2
START_POSITION_POINTER=0x7C3688
END_POSITION_POINTER=0x7C4A98

SONIC_START_POSITIONX=0
SONIC_START_POSITIONY=-95
SONIC_START_POSITIONZ=1060
SONIC_START_PITCH=32768
SONIC_START_MODE=0
SONIC_START_RUNNING=0

SONIC_END_POSITIONX=500
SONIC_END_POSITIONY=-920
SONIC_END_POSITIONZ=-51035
SONIC_END_PITCH=6371

DARK_START_POSITIONX=0
DARK_START_POSITIONY=0
DARK_START_POSITIONZ=0
DARK_START_PITCH=0
DARK_START_MODE=0
DARK_START_RUNNING=0

DARK_END_POSITIONX=0
DARK_END_POSITIONY=0
DARK_END_POSITIONZ=0
DARK_END_PITCH=0

ROSE_START_POSITIONX=0
ROSE_START_POSITIONY=0
ROSE_START_POSITIONZ=0
ROSE_START_PITCH=0
ROSE_START_MODE=0
ROSE_START_RUNNING=0

ROSE_END_POSITIONX=0
ROSE_END_POSITIONY=0
ROSE_END_POSITIONZ=0
ROSE_END_PITCH=0

CHAOTIX_START_POSITIONX=0
CHAOTIX_START_POSITIONY=0
CHAOTIX_START_POSITIONZ=0
CHAOTIX_START_PITCH=0
CHAOTIX_START_MODE=0
CHAOTIX_START_RUNNING=0

CHAOTIX_END_POSITIONX=0
CHAOTIX_END_POSITIONY=0
CHAOTIX_END_POSITIONZ=0
CHAOTIX_END_PITCH=0

FOREDIT_START_POSITIONX=0
FOREDIT_START_POSITIONY=0
FOREDIT_START_POSITIONZ=0
FOREDIT_START_PITCH=0
FOREDIT_START_MODE=0
FOREDIT_START_RUNNING=0

FOREDIT_END_POSITIONX=0
FOREDIT_END_POSITIONY=0
FOREDIT_END_POSITIONZ=0
FOREDIT_END_PITCH=0

