HEROES_MOD_LOADER_LEVEL_CONFIG_FILE
LEVEL_FLAG=GrandMetropolis

PUSH_INSTRUCTION_POINTER=0x576E5C
START_POSITION_POINTER=0x7C30E8
END_POSITION_POINTER=0x7C4688

SONIC_START_POSITIONX=0
SONIC_START_POSITIONY=0
SONIC_START_POSITIONZ=0
SONIC_START_PITCH=32768
SONIC_START_MODE=0
SONIC_START_RUNNING=0

SONIC_END_POSITIONX=0
SONIC_END_POSITIONY=0
SONIC_END_POSITIONZ=0
SONIC_END_PITCH=0

DARK_START_POSITIONX=0
DARK_START_POSITIONY=0
DARK_START_POSITIONZ=0
DARK_START_PITCH=32768
DARK_START_MODE=0
DARK_START_RUNNING=0

DARK_END_POSITIONX=0
DARK_END_POSITIONY=0
DARK_END_POSITIONZ=0
DARK_END_PITCH=0

ROSE_START_POSITIONX=0
ROSE_START_POSITIONY=0
ROSE_START_POSITIONZ=0
ROSE_START_PITCH=32768
ROSE_START_MODE=0
ROSE_START_RUNNING=0

ROSE_END_POSITIONX=0
ROSE_END_POSITIONY=0
ROSE_END_POSITIONZ=0
ROSE_END_PITCH=0

CHAOTIX_START_POSITIONX=0
CHAOTIX_START_POSITIONY=0
CHAOTIX_START_POSITIONZ=0
CHAOTIX_START_PITCH=32768
CHAOTIX_START_MODE=0
CHAOTIX_START_RUNNING=0

CHAOTIX_END_POSITIONX=0
CHAOTIX_END_POSITIONY=0
CHAOTIX_END_POSITIONZ=0
CHAOTIX_END_PITCH=0

FOREDIT_START_POSITIONX=0
FOREDIT_START_POSITIONY=0
FOREDIT_START_POSITIONZ=0
FOREDIT_START_PITCH=32768
FOREDIT_START_MODE=0
FOREDIT_START_RUNNING=0

FOREDIT_END_POSITIONX=0
FOREDIT_END_POSITIONY=0
FOREDIT_END_POSITIONZ=0
FOREDIT_END_PITCH=0

